---
- name: manage EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: set instance state
      ec2:
         key_name: "{{ lookup('env', 'AWS_SSH_KEY_ID') }}"
         instance_ids: "{{ instance_id  | default(omit) }}"
         state: "{{ instance_state }}"
         instance_type: m4.large
         image: ami-430b1a55
         assign_public_ip: yes
         vpc_subnet_id: subnet-a9c7b484
         wait: yes
         instance_tags:
           Name: Conjur CE
           Description: Used as the basis for the Conjur CE AMI
           Version: "{{ lookup('env', 'CONJUR_VERSION') }}"

      register: ec2
