---

- name: Render CloudFormation template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Grab AMIs from vars-amis.json
      include_vars:
        file: vars-amis_by_region.json
        name: amis_by_region
      
    - name: Insert AMI IDs into template
      template:
        src: /ansible/templates/cfn/conjur.yml.j2
        dest: "{{ item }}"
      with_items:
        - /ansible/conjur.yml
        - "/ansible/conjur-{{ conjur_version}}.yml"
