---

- name: Render CloudFormation template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Insert AMI IDs into template
      template:
        src: /ansible/templates/cfn/conjur.yml.j2
        dest: /ansible/conjur.yml
