---
- name: Manage Conjur stack

  hosts: localhost
  connection: local

  tasks:
    - name: manage cluster
      cloudformation:
        stack_name: "{{ stack_name }}"
        state: "{{ stack_state }}"
        disable_rollback: no
        template: /ansible/conjur.yml
        template_parameters:
          # Don't specify ImageId, we want the default that got added by fetch-cft.yml
          InstanceType: m4.large
          KeyName: "{{ lookup('env', 'AWS_SSH_KEY_ID') }}"
          ConjurAccount: test
          ConjurAdminPassword: secret
          DBAdminPassword: secretdbpassword
          DBDeletionPolicy: Delete
          VpcId: vpc-36803e50
          VpcSubnetIds: "subnet-a9c7b484,subnet-f10c2cb8"
      register: stack
