---
- name: Test Conjur CE cluster
  hosts: localhost
  connection: local
  vars:
    test_stack: yes

  tasks:
    - name: manage cluster
      cloudformation:
        stack_name: "{{ stack_name }}"
        state: "{{ (test_stack | bool) | ternary('present', 'absent') }}"
        disable_rollback: no
        template: /ansible/conjur-ce.yml
        template_parameters:
          KeyName: "{{ lookup('env', 'AWS_SSH_KEY_ID') }}"
          ImageId: "{{ lookup('env', 'AMI_ID') }}"
          ConjurAccount: test
          ConjurAdminPassword: secret
          DBAdminPassword: secretdbpassword
          VpcId: vpc-36803e50
          VpcSubnetIds: "subnet-a9c7b484,subnet-f10c2cb8"
      register: stack

    - name: test cluster
#      uri:
#        method: OPTIONS
#        url: "http://{{ stack.stack_outputs['ConjurAddress'] }}"
      command: "curl -vs -X OPTIONS http://{{ stack.stack_outputs['ConjurAddress'] }}"
      register: result
      until: result.rc == 0
      retries: 5
      delay: 30
      when: test_stack
