---
- include: stack.yml stack_state=present

- name: Test Conjur CE cluster
  hosts: localhost
  connection: local

  tasks:
    - name: Wait for instance
      local_action:
        wait_for port=22 host='{{ stack.stack_outputs['ConjurAddress'] }}' search_regex=OpenSSH
      with_items: "{{ ec2.instances }}"

    - name: test cluster
      command: "curl -vs -X OPTIONS http://{{ stack.stack_outputs['ConjurAddress'] }}"
      register: result
      until: result.rc == 0
      retries: 20
      delay: 60
