---
- name: Create Conjur CE cluster
  hosts: localhost
  connection: local

  tasks:
    - name: start cluster
      cloudformation:
        stack_name: "{{ stack_name }}"
        state: present
        disable_rollback: no
        template: /ansible/conjur-ce.yml
        template_parameters:
          KeyName: "{{ lookup('env', 'AWS_SSH_KEY_ID') }}"
          ImageId: "{{ lookup('env', 'AMI_ID') }}"
          ConjurAccount: test
          ConjurAdminPassword: secret
          DBAdminPassword: secretdbpassword
          VpcId: vpc-36803e50
          VpcSubnetIds: "subnet-a9c7b484,subnet-f10c2cb8"
      register: stack

    - name: test cluster
#      uri:
#        method: OPTIONS
#        url: "http://{{ stack.stack_outputs['ConjurAddress'] }}"
      command: "curl -vs -X OPTIONS http://{{ stack.stack_outputs['ConjurAddress'] }}"

- name: Tear down Conjur CE cluster
  hosts: localhost
  connection: local
  vars:
    terminate_after_test: yes

  tasks:
    - name: stop cluster
      cloudformation:
        stack_name: "{{ stack_name }}"
        state: absent
      when: terminate_after_test
